### PR TITLE
Distributed Scheduler

### PR DESCRIPTION
**Pull request by cherrypiejam**
Basic functionalities implemented, but not quite mergeable 
Needs to do:
1. Place timestamps for stats
2. Refactor message structs for RPCs
3. Add better error handling (currently ad hoc)
4. Refine remote resource manager

### CODE REVIEW

**Comment by alevy** [comment]
@cherrypiejam this is a reasonably big PR (understandably). Could you maybe briefly summarize what the pieces are? Or what the design is, so we know what to look for? Also, since this is a draft still, what's outsanding and/or what might be particularly useful feedback.

**Comment by tan-yue** [comment]
I think we can make the base branch of this PR to be `master`.

**Comment by cherrypiejam** [comment]
> @cherrypiejam this is a reasonably big PR (understandably). Could you maybe briefly summarize what the pieces are? Or what the design is, so we know what to look for? Also, since this is a draft still, what's outsanding and/or what might be particularly useful feedback.

Absolutely. `sched/` consists of some basic components of a distributed scheduler. In `sched/gateway.rs`, there are two structs: `HTTPGateway` is exactly the same old `gateway.rs`, listening for requests from outside worlds; `SchedGateway` (horrible name, I know) listens for RPC calls from workers, and each RPC call is a connection. Once it receives a connection, it spawns another thread to process the call based on the message type which can be found in `sched/message.rs` & `sched/messages.proto`. 

`sched/resource_manager.rs`, as its name says, is to manage global resources for the scheduler. It coexists with `resource_manager.rs` because each worker node (machine) maintains its own resource manager to handle the actual VM launches and evictions. The global resource manager, in `sched/resource_manager.rs`, mainly is to maintain a view of cached VMs and idle worker threads for each worker node and thus helps to make scheduling decisions. 

`sched/mod.rs` contains two parts. The first part is `fn schedule()`, and it is to schedule an HTTP request to a remote worker thread based on the global resource manager. The second part implements `struct Scheduler{}` which provides interfaces for workers to make RPC calls. 

`bin/multivm/main.rs` is the modified version of the old `multivm` to use the distributed scheduler. I'll further make two separate binaries to test it on multiple machines. Moreover, I replaced channels in `vm.rs` and `worker.rs` with RPC calls and that's it.

**Comment by cherrypiejam** [comment]
> I think we can make the base branch of this PR to be `master`.

I can do that. I was building it on top of `feat/faasten` so I'll need some time to do that

**Pull request closed without merging**
